config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users, only: [:show, :index, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # @user = User.new(username: params[:username], email: params[:email], password: params[:password])


    if @user.save
      redirect_to new_user_path, notice: 'User created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to root_path, notice: 'User updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReFormerRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_with(model: @user) do |form| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <label for="username">Username:</label>
    <%= form.text_field :username %>
    
    <label for="email">Email Address:</label>
    <%= form.email_field :email %>

    <label for="password">Very Secure Password Please:</label>
    <%= form.password_field :password %>

    <%= form.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <div>
        <p><%= user.username %></p>
        <p><%= user.email %></p>
        <p><%= user.password %></p>
        <a href="<%= edit_user_path(user) %>">Edit</a>
    </div>
<% end %>

app/views/users/new.html.erb
<!-- Form for creating a new user -->

<!--
<form accept-charset="UTF-8" action="/users" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="name">Name:</label>
    <input type="text" name="user[username]" id="username">
    
    <label for="email">Email:</label>
    <input type="email" name="user[email]" id="email">

    <label for="password">Password:</label>
    <input type="password" name="user[password]" id="password">

    <input type="submit" value="Create User">
</form>
-->

<!--
<%= form_tag('/users', method: 'post') do %>
    <label for="username">Name:</label>
    <%= text_field_tag :username %>
    
    <label for="email">Email:</label>
    <%= email_field_tag :email %>

    <label for="password">Password:</label>
    <%= password_field_tag :password %>

    <%= submit_tag "Create User" %>
<% end %>
-->

<%= form_with(model: @user) do |form| %>
    <label for="username">Username:</label>
    <%= form.text_field :username %>
    
    <label for="email">Email Address:</label>
    <%= form.email_field :email %>

    <label for="password">Very Secure Password Please:</label>
    <%= form.password_field :password %>

    <%= form.submit "Create User" %>
<% end %>